### ISSUE TITLE
NotesGrid.jsx - неиспользуемая переменная

### ISSUE THREAD

**Issue by maplemap** [krambertech/spa-webinar#2]
В файле [NotesGrid.jsx](https://github.com/krambertech/spa-webinar/blob/master/client/components/NotesGrid.jsx) заметил переменную **onNoteDelete**, которая не используется (строка 10). Забавно то, что в 29 строке, где должна быть эта переменная, все срабатывает, а ведь не должно было (контекст не тот). В своей копии этот момент правил ибо не работало. В чем волшебство?

**Comment by krambertech** [comment]
Да, переменная лишняя, я удалила. В следующий раз можешь cразу создать пул-реквест. Там все работает из-за использования стрелочных функций, в них сохраняется контекст.

**Comment by krambertech** [comment]
https://youtu.be/syo6HPFTGt4?t=9m12s

**Comment by maplemap** [comment]
Да, спасибо, увидел теперь на практике. Из-за этого и пулл-реквеста не было, потому что не было уверенности.
